# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "order-protection"
handle = "order-protection"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.shipping-option-list.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true
block_progress = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[settings]
  [[settings.fields]]
  key = "graphqlId"
  type = "single_line_text_field"
  name = "Order Protection Product"
  description = "Enter 'admin_graphql_api_id' of the product from its json"

  [[settings.fields]]
  key = "heading"
  type = "single_line_text_field"
  name = "Section Heading"
  description = "Enter section heading"

  [[settings.fields]]
  key = "sub_heading"
  type = "single_line_text_field"
  name = "Sub Heading"
  description = "Enter heading for order protection section"

  [[settings.fields]]
  key = "description_line_1"
  type = "multi_line_text_field"
  name = "Description - Line 1"
  description = "Enter first line of description"

  [[settings.fields]]
  key = "description_line_2"
  type = "multi_line_text_field"
  name = "Description - Line 2"
  description = "Enter second line of description"